language: java

dist: trusty

jdk:
  - oraclejdk8

sudo: false

script:
  - mvn clean
  - mvn evosuite:generate
  - mvn evosuite:export
  - mvn test -Dtest="CustomTestAVLTree"
  - mvn test
  - "mvn cobertura:cobertura"
  - bash <(curl -s https://codecov.io/bash)

after_success:
  - bash <(curl -s https://codecov.io/bash)
