language: java

dist: trusty

jdk:
  - oraclejdk8

sudo: false

script:
  - mvn clean
  - mvn evosuite:generate
  - mvn evosuite:export
  - mvn test
  - mvn evosuite:info

after_success:
  - bash <(curl -s https://codecov.io/bash)